### ISSUE TITLE
Analyzer 'CompanialCopAnalyzer.Design.Rule0027AnalyzeTransferField' threw an exception

### ISSUE THREAD

**Issue by finnpedersenkazes** [Companial/CompanialCop#2]
I am getting the following error message

````
Analyzer 'CompanialCopAnalyzer.Design.Rule0027AnalyzeTransferField' threw an exception of type 'System.InvalidCastException' with message 'System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.CodeunitSyntax' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.TableExtensionSyntax'.
   at CompanialCopAnalyzer.Design.Rule0027AnalyzeTransferField.AnalyzeTableExtension(SyntaxNodeAnalysisContext ctx)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass53_1.<ExecuteSyntaxNodeAction>b__1() in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 752
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1088'
````

<img width="650" alt="Screenshot 2024-04-14 141037" src="https://github.com/Companial/CompanialCop/assets/5465703/08ab3766-c966-4e6d-8476-98779b6bf0cd">

The below warnings about the argument not being user is not correct as illustrated in the image. 

<img width="617" alt="Screenshot 2024-04-14 141206" src="https://github.com/Companial/CompanialCop/assets/5465703/3a17f48e-2fd4-4ac8-b4ec-957d95480c65">

This has worked before. I am not sure what is new. I have downloaded the latest symbols. 

Hope it helps. 
Finn

**Comment by tinestaric** [comment]
Hey, 
thanks for reporting this. I've just published a new release. Can you check if it works okay with that one?
